import 'dart:math';
import 'package:hive_ce_flutter/hive_ce_flutter.dart';

/// Manages the daily inspirational quote cycle.
/// Quotes are exclusive to push notifications — never displayed inside the app.
class QuoteService {
  static const _boxName = 'quote_state';
  static const _orderKey = 'shuffled_order';
  static const _cycleStartKey = 'cycle_start_ms';

  static Box? _box;

  /// Call after HiveService.init().
  static Future<void> init() async {
    _box = await Hive.openBox(_boxName);
    _ensureCycleInitialized();
  }

  static void _ensureCycleInitialized() {
    final today = _dateOnly(DateTime.now());
    final cycleStartMs = _box!.get(_cycleStartKey) as int?;
    final rawOrder = _box!.get(_orderKey);

    if (cycleStartMs == null || rawOrder == null) {
      _resetCycle(today);
      return;
    }

    final cycleStart = DateTime.fromMillisecondsSinceEpoch(cycleStartMs);
    if (today.difference(cycleStart).inDays >= quotes.length) {
      // Full cycle complete — advance start by exactly 365 days and re-shuffle.
      _resetCycle(cycleStart.add(Duration(days: quotes.length)));
    }
  }

  static void _resetCycle(DateTime cycleStart) {
    final order = List<int>.generate(quotes.length, (i) => i)..shuffle(Random());
    _box!.put(_orderKey, order);
    _box!.put(_cycleStartKey, cycleStart.millisecondsSinceEpoch);
    print('[QuoteService] New 365-day cycle started: $cycleStart');
  }

  /// Returns the quote assigned to [date] within the current cycle.
  static ({String text, String author}) getQuoteForDate(DateTime date) {
    final cycleStartMs = _box!.get(_cycleStartKey) as int?;
    final rawOrder = _box!.get(_orderKey);

    if (cycleStartMs == null || rawOrder == null) {
      return (text: quotes[0].$1, author: quotes[0].$2);
    }

    final cycleStart = DateTime.fromMillisecondsSinceEpoch(cycleStartMs);
    final dayIndex =
        _dateOnly(date).difference(cycleStart).inDays.clamp(0, quotes.length - 1);
    final order = List<int>.from(rawOrder as List);
    final q = quotes[order[dayIndex]];
    return (text: q.$1, author: q.$2);
  }

  static ({String text, String author}) getTodayQuote() =>
      getQuoteForDate(DateTime.now());

  static DateTime _dateOnly(DateTime dt) => DateTime(dt.year, dt.month, dt.day);

  // ---------------------------------------------------------------------------
  // 365 curated quotes — push notifications only, not shown inside the app
  // ---------------------------------------------------------------------------
  static const List<(String, String)> quotes = [
    ("A memória nos permite reunir os fragmentos que foram dispersos.", "bell hooks"),
    ("Nossos passos vêm de longe.", "Sueli Carneiro"),
    ("A memória é um exercício de esperança.", "Paulo Freire"),
    ("A vida é como um livro. Só depois de ler sabemos o que há dentro. Vivemos.", "Carolina Maria de Jesus"),
    ("O futuro é aqui e agora, pode ser que não haja amanhã.", "Ailton Krenak"),
    ("A educação é o ato de produzir em cada indivíduo a humanidade.", "Dermeval Saviani"),
    ("A nossa escrevivência não pode ser escrita por mãos alheias.", "Conceição Evaristo"),
    ("A rotina é feita de pequenos milagres invisíveis. Não deixe o de hoje sumir.", "Ana Liz"),
    ("A cura acontece no detalhe do cotidiano que decidimos olhar.", "Roberta Rocha"),
    ("Gravar um segundo é dizer para o tempo: eu te vi.", "Ana Liz"),
    ("Respeitar o seu tempo cíclico é um ato de rebeldia. Qual foi o ritmo do seu dia hoje?", "Mandala Lunar"),
    ("Não se esqueça do vídeo de hoje. Sua história importa.", "Retro1"),
    ("Pessoas gordas têm o direito de ocupar espaços sem pedir licença.", "Malu Jimenez"),
    ("Meu corpo é o lugar onde eu vivo. Eu o ocupo com toda a sua história.", "Roxane Gay"),
    ("Nada é absoluto. Tudo muda, tudo se move, tudo gira, tudo voa e desaparece.", "Frida Kahlo"),
    ("O lugar em que a gente está determina o pensamento.", "Lélia Gonzalez"),
    ("Tecer o cotidiano é não deixar a vida passar sem ser vista.", "Ana Liz"),
    ("Recordar é passar novamente pelo coração. O que seu coração sentiu hoje?", "Roberta Rocha"),
    ("O autoconhecimento é uma jornada de libertação.", "Djamila Ribeiro"),
    ("A memória não é um depósito do passado, mas o chão onde se pisa para construir o futuro.", "Paulo Freire"),
    ("Somos o que fazemos, mas somos, principalmente, o que fazemos para mudar o que somos.", "Eduardo Galeano"),
    ("A gente não nasce negro, a gente se torna negro. É uma conquista dura, cruel e que se faz no dia a dia.", "Lélia Gonzalez"),
    ("Cuidar de mim mesma não é autoindulgência, é autopreservação, e isso é um ato de guerra política.", "Audre Lorde"),
    ("A memória é o que nos permite contar a nossa própria história.", "Grada Kilomba"),
    ("Memória é o que resta quando o dia termina. O que você escolheu guardar?", "Retro1"),
    ("Para educar as crianças, é preciso todo um quilombo.", "Abigail Campos Leal"),
    ("A identidade é um rio que se move, uma fronteira que se cruza.", "Gloria Anzaldúa"),
    ("Não sou o que sou, sou o que estou sendo.", "Sabotage"),
    ("O mundo é diferente da ponte pra cá.", "Racionais MC's"),
    ("Eu não sou o que aconteceu comigo, eu sou o que escolho me tornar.", "Octavia Butler"),
    ("Tudo o que você toca, você muda. Tudo o que você muda, muda você.", "Octavia Butler"),
    ("O meu estilo de ser é o estilo de ser de cada um.", "Stella do Patrocínio"),
    ("A globalização é o ápice do processo de alienação do território.", "Milton Santos"),
    ("A gente só conhece o mundo quando a gente o transforma.", "Darcy Ribeiro"),
    ("Escrever é o ato de existir na página quando o mundo nos nega.", "Carolina Maria de Jesus"),
    ("A liberdade é uma prática, não um destino.", "Angela Davis"),
    ("O registro do hoje é a munição para as lutas de amanhã.", "Frantz Fanon"),
    ("Memória é o que a gente usa para adiar o fim do mundo.", "Ailton Krenak"),
    ("O tempo da vida não é o tempo do relógio da fábrica.", "Silvia Federici"),
    ("A poesia não é um luxo, é uma necessidade vital.", "Audre Lorde"),
    ("A herança é o que a gente constrói com o que nos deixaram.", "Fred Moten"),
    ("Temos que ter cuidado para não nos tornarmos o que estamos combatendo.", "Samuel R. Delany"),
    ("A arte é a nossa forma de respirar debaixo d'água.", "Denise Ferreira da Silva"),
    ("Um país sem memória é um país sem futuro.", "Darcy Ribeiro"),
    ("O futuro é ancestral.", "Célia Xakriabá"),
    ("O mundo precisa ser reflorestado, começando pelo nosso pensamento.", "Geni Núñez"),
    ("Nossa memória é a nossa maior tecnologia de sobrevivência.", "Daiara Tukano"),
    ("Eu sou um corpo, um ser, um nó; o tempo é um sopro.", "Luedji Luna"),
    ("Onde o corpo possa ser o que se é, sem medo de ser.", "Liniker"),
    ("Escrever é curar o silêncio que nos impuseram.", "Eliane Potiguara"),
    ("A ancestralidade é um caminho que se faz andando para trás e para frente.", "Juçara Marçal"),
    ("Viver é o único jeito de não morrer.", "Jota.pê"),
    ("A beleza é um direito, não um privilégio.", "Jéssica Balbino"),
    ("A vida é o que a gente faz dela, enquanto a gente faz.", "A Banda Mais Bonita da Cidade"),
    ("O que a gente tem é o agora, e o agora é um presente.", "Gilsons"),
    ("A ternura é uma ferramenta de resistência política.", "Chimamanda Ngozi Adichie"),
    ("A voz da mulher indígena é o grito da terra que resiste.", "Sueli Maxakali"),
    ("Escrever é um modo de dar ordem ao caos do mundo.", "Elena Ferrante"),
    ("A educação é a arma mais poderosa que você pode usar para mudar o mundo.", "Nelson Mandela"),
    ("Ninguém pode me impedir de fazer o que eu quero, eu sou livre.", "Malala Yousafzai"),
    ("Minha pátria não é uma mala, e eu não sou um passageiro.", "Mahmoud Darwish"),
    ("Nós, mulheres, somos as tecelãs da história que o silêncio tentou apagar.", "Eme Sald"),
    ("O feminismo negro é a chave para entender a liberdade de todos.", "Lélia Gonzalez"),
    ("A leitura de uma mulher é um ato de insurreição.", "Leia Mulheres"),
    ("O tempo da colheita depende da paciência com que plantamos a memória.", "Graça Graúna"),
    ("Cuidar da nossa história é o primeiro passo para a soberania do nosso corpo.", "Oyèrónké Oyěwùmí"),
    ("A memória palestina é um ato de resistência contra o esquecimento.", "Edward Said"),
    ("Não há nada mais forte do que uma mulher que se reconstruiu.", "Hannah Arendt"),
    ("A vida é um sopro, mas o registro é eterno.", "Stella do Patrocínio"),
    ("Nossa cultura é a nossa raiz; sem ela, somos apenas sombras.", "Wangari Maathai"),
    ("Onde quer que haja injustiça, haverá uma mulher narrando a verdade.", "Nawal El Saadawi"),
    ("A memória é quem nos remete ao princípio de tudo, às origens. Somos fio na teia da vida.", "Daniel Munduruku"),
    ("Brasil, o que faço com a minha cara de índia? Não sou violência, eu sou história.", "Eliane Potiguara"),
    ("A escrita é uma arma para manter a aldeia viva dentro da gente.", "Márcia Wayna Kambeba"),
    ("Nossa herança não é o que nos deixaram, mas o que fazemos com o que restou.", "Ailton Krenak"),
    ("O perigo de uma única história é que ela rouba a dignidade das pessoas.", "Chimamanda Ngozi Adichie"),
    ("A cultura não faz as pessoas. As pessoas fazem a cultura.", "Chimamanda Ngozi Adichie"),
    ("O coração de uma pessoa é como um oceano; tem segredos nas profundezas.", "Mariama Bâ"),
    ("A amizade tem grandezas que o amor não conhece.", "Mariama Bâ"),
    ("Eu não vou ser estatística, eu vou ser a música que você não consegue parar de ouvir.", "Suheir Hammad"),
    ("Minha vida é o meu único território soberano.", "Suheir Hammad"),
    ("Não há nada mais político do que a alegria de uma mulher negra.", "Abigail Campos Leal"),
    ("Nossa herança é a terra, mas nossa riqueza é a memória.", "Suheir Hammad"),
    ("Livros e educação são as únicas coisas que ninguém pode tirar de você.", "Mariama Bâ"),
    ("Seja a história que você quer que contem sobre o seu tempo.", "Chimamanda Ngozi Adichie"),
    ("Fotografar é colocar na mesma linha de mira a cabeça, o olho e o coração.", "Henri Cartier-Bresson"),
    ("A imagem é o que nos resta quando o tempo tenta nos convencer de que não estivemos lá.", "Ana Liz"),
    ("Descolonizar o olhar é aprender a ver beleza na nossa própria história.", "Geni Núñez"),
    ("Minha arte é o espelho onde o mundo se vê sem filtros.", "Sabotage"),
    ("Nossa cara de índia não é fantasia, é o registro de que o Brasil começou aqui.", "Eliane Potiguara"),
    ("O que não é registrado, o vento leva. O que é guardado, a história herda.", "Provérbio Africano"),
    ("Toda foto de uma mulher gorda sorrindo é um manifesto de liberdade.", "Malu Jimenez"),
    ("A memória é o único paraíso do qual não podemos ser expulsos.", "Jean Paul"),
    ("Eu gravo para que o esquecimento não tenha a última palavra.", "Suheir Hammad"),
    ("Minha câmera é minha arma contra o silêncio.", "Zanele Muholi"),
    ("A vida acontece no intervalo entre um segundo e outro.", "Jota.pê"),
    ("Se a gente não conta nossa história, alguém vai contar errado no nosso lugar.", "Djamila Ribeiro"),
    ("O hoje faz parte de uma longa caminhada.", "Ana Liz"),
    ("Um segundo de hoje, um fio de humanidade para o amanhã.", "Ana Liz"),
    ("Teça sua história: registre o retalho de humanidade que viveu hoje.", "Ana Liz"),
    ("O que resta de nós é o que guardamos. Tecer o hoje é um ato de humanidade.", "Ana Liz"),
    ("O mundo é imenso, mas sua humanidade cabe nesse segundo. Registre.", "Ana Liz"),
    ("Viver é raro.", "Ana Liz"),
    ("Sua existência é um documento histórico. Guarde o seu pedaço de mundo hoje.", "Ana Liz"),
    ("Contra o apagamento do tempo: o brilho da sua humanidade em um segundo.", "Ana Liz"),
    ("A vida passa, mas a humanidade fica nos detalhes que a gente decide ver. Registre o seu hoje.", "Ana Liz"),
    ("Sashay away, esquecimento! Hoje meu segundo é puro close.", "Gíria Drag"),
    ("O brilho da sua existência não é glitter, é história. Registre.", "Afeto Queer"),
    ("O corpo não é um ser, mas uma fronteira em movimento.", "Judith Butler"),
    ("A identidade é uma prática cotidiana; registre quem você escolheu ser hoje.", "Judith Butler"),
    ("Ninguém nasce mulher, mas a gente se torna... e esse tornar-se é uma luta diária.", "Simone de Beauvoir / Judith Butler"),
    ("Existir é um ato de resistência; narrar a própria existência é um ato de liberdade.", "Helena Vieira"),
    ("Nossos corpos são territórios de escrita. O que você escreveu no mundo hoje?", "Helena Vieira"),
    ("A memória é o que impede que a nossa história seja contada apenas pelo olhar do outro.", "Helena Vieira"),
    ("O gênero é uma performance que se repete. Qual foi o close do seu dia?", "Judith Butler"),
    ("A vida trans é uma lição de que o destino não é nossa biografia.", "Helena Vieira"),
    ("Não precisamos de permissão para ocupar o espaço com a nossa verdade.", "Judith Butler"),
    ("Não subestime o poder de um segundo de felicidade. Ele é político.", "Audre Lorde"),
    ("A norma tenta nos apagar, mas o nosso vídeo diz: eu estou aqui.", "Judith Butler"),
    ("A fronteira não é apenas um lugar, é uma forma de vida. Registre seus passos nessa travessia.", "Glória Anzaldúa"),
    ("Onde quer que eu esteja, eu sou o meu próprio território. Como você ocupou o seu hoje?", "Glória Anzaldúa"),
    ("Descolonizar o gênero é retomar o direito de ser múltipla. Qual versão de você viveu hoje?", "María Lugones"),
    ("Grave sua história antes que as fronteiras do mundo tentem defini-la por você.", "Glória Anzaldúa"),
    ("Nosso corpo é nossa primeira memória política. Registre a força que ele carregou hoje.", "Rita Segato"),
    ("A soberania sobre o que vivemos começa no olhar que lançamos sobre nós mesmas.", "Rita Segato"),
    ("Não deixe que o silêncio histórico apague o brilho da sua trajetória hoje.", "Helena Vieira"),
    ("Educar é um ato comunitário de tecer o futuro. O que você plantou hoje?", "Julieta Paredes"),
    ("Desobedecer ao padrão é o close mais revolucionário que você pode dar.", "Ochy Curiel"),
    ("A memória coletiva se constrói com a soma dos nossos segundos individuais.", "Julieta Paredes"),
    ("O tempo decolonial é o tempo do afeto e da presença. Você esteve aqui hoje?", "Yuderkys Espinosa"),
    ("Retomar a própria voz nas redes é uma ferramenta de sobrevivência política.", "Ana Liz"),
    ("Afirmar o próprio nome e a própria história é um gesto de reconhecimento e reciprocidade.", "Ana Liz"),
    ("A música e o registro atravessam o tempo e ativam memórias que não morrem.", "Ana Liz"),
    ("Nossa história não é um objeto de estudo, é um território vivo. Registre sua voz.", "María Lugones"),
    ("Escrever-se é desobedecer ao silêncio que tentaram nos impor.", "Ochy Curiel"),
    ("O cotidiano é o lugar onde a gente tece a nossa própria descolonização.", "Julieta Paredes"),
    ("Grave o seu hoje para que o amanhã não seja contado por mãos alheias.", "Yuderkys Espinosa"),
    ("A vida é um fluxo de resistências. Qual foi o seu gesto de liberdade hoje?", "Karina Bidaseca"),
    ("Viver sem a obrigação de ser didática é a minha maior liberdade.", "Ana Liz"),
    ("Flor e ser, florescer: continuar resistindo e criando raízes para se fortalecer.", "Ana Liz"),
    ("O blasé do cotidiano às vezes pode te surpreender. Registre o detalhe.", "Ana Liz"),
    ("Fazer-se presente é demarcar o tempo com a própria existência. Você está aqui.", "Ana Liz"),
    ("Grave para não esquecer quem foi, para honrar quem é e para ter sabedoria ao decidir quem será.", "Ana Liz"),
    ("Mudar o que seremos exige a coragem de olhar para o que fomos. Registre sua evolução.", "Rita Segato"),
    ("Ser parte de um lugar é deixar nele o rastro da sua história. Qual rastro você deixou hoje?", "María Lugones"),
    ("A sabedoria mora na fresta entre a memória e a mudança. Capture esse instante.", "Ana Liz"),
    ("Não esqueça de quem você é no meio do caminho. Seu segundo de hoje é sua bússola.", "Ana Liz"),
    ("Mudar é um direito decolonial; registrar a mudança é um ato de soberania.", "Yuderkys Espinosa"),
    ("Uma das maiores dores de ser imigrante é ter que provar seu potencial enquanto não fluente na língua.", "Ana Liz"),
    ("Minha inteligência não tem sotaque. Registro meu saber para não esquecer meu valor.", "Gloria Anzaldúa"),
    ("Habitar uma língua estrangeira é um exercício de coragem. Grave sua voz hoje.", "Gloria Anzaldúa"),
    ("Não deixe que a barreira da língua apague a grandiosidade da sua trajetória.", "Ana Liz"),
    ("Migrar é levar o seu território dentro do peito. Qual parte da sua terra você viveu hoje?", "María Lugones"),
    ("Eu não preciso provar nada a ninguém; meu registro é o meu próprio porto seguro.", "Ana Liz"),
    ("Hora do seu close diário:", "Retro1"),
    ("Não deixe o tempo apagar o que de bom a gente viveu.", "Sandy & Junior"),
    ("Um toque de sabedoria:", "Retro1"),
    ("A gente aprende a ser feliz com o que o tempo traz.", "Sandy & Junior"),
    ("Nada vai apagar o que o tempo escreveu.", "Sandy & Junior"),
    ("Viver é aprender a todo momento.", "Sandy & Junior"),
    ("O amanhã a gente faz agora.", "Sandy & Junior"),
    ("O tempo é o espírito do mundo.", "Gilberto Gil"),
    ("É preciso ter cuidado para mais tarde não sofrer.", "Cartola"),
    ("O sol há de brilhar mais uma vez.", "Nelson Cavaquinho"),
    ("Viver e não ter a vergonha de ser feliz.", "Gonzaguinha"),
    ("Eu sou o sinal da minha própria história.", "Liniker"),
    ("O que eu escrevo é um rastro de mim.", "Carola Saavedra"),
    ("A memória é uma ilha de edição.", "Waly Salomão"),
    ("Minha história é o meu maior patrimônio.", "Jarid Arraes"),
    ("Escrever é desatar nós.", "Aline Bei"),
    ("O importante é ser você, mesmo que seja estranho.", "Pitty"),
    ("Seja sua própria inspiração.", "Lizzo"),
    ("O ontem é história, o amanhã é mistério, mas o hoje é uma dádiva.", "Kung Fu Panda"),
    ("A memória é o que nos salva da morte em vida.", "Itamar Vieira Junior"),
    ("Não tenha medo de se olhar no espelho. Quebre o vidro.", "Eliane Brum"),
    ("Narrar o próprio trauma é o começo da cura política.", "Aline Bei"),
    ("A nossa existência é o maior erro no sistema do opressor.", "Jarid Arraes"),
    ("O afeto entre nós é uma tecnologia de sobrevivência.", "Carla Akotirene"),
    ("Minha ancestralidade não é passado, é o futuro que eu estou construindo.", "Cidinha da Silva"),
    ("A escrita é o quilombo que eu construo todos os dias.", "Genivaldo Amâncio"),
    ("Não há democracia sem a memória das nossas lutas.", "Flávia Oliveira"),
    ("Amar e mudar as coisas me interessa mais.", "Belchior"),
    ("A gente não quer só comida, a gente quer comida, diversão e arte.", "Arnaldo Antunes / Titãs"),
    ("Respeite meu sotaque, minha cor e minha história.", "BaianaSystem"),
    ("O meu corpo é o meu país, e eu sou a única lei.", "Linn da Quebrada"),
    ("Quem não se movimenta, não sente as correntes que o prendem.", "Rosa Luxemburgo"),
    ("Ano passado eu morri, mas esse ano eu não morro.", "Belchior"),
    ("O novo sempre vem.", "Belchior"),
    ("Viver é melhor que sonhar.", "Elis Regina"),
    ("A minha alucinação é suportar o dia a dia.", "Belchior"),
    ("Não sou perigoso, segure a minha mão. Sou apenas um homem latino-americano.", "Belchior"),
    ("A vida é curta, mas é larga.", "Cássia Eller"),
    ("Para que usar antena de TV, se a gente pode usar a nossa própria cabeça?", "Rita Lee"),
    ("O meu bem-estar não depende do seu mal-estar.", "Rita Lee"),
    ("Não me leve a mal, me leve a sério.", "Rita Lee"),
    ("O mundo é um moinho, vai triturar teus sonhos... então grave-os agora.", "Cartola / Cássia Eller"),
    ("Ocupar o palco da própria vida é o primeiro ato de rebeldia.", "Augusto Boal"),
    ("Não basta entender o mundo, é preciso sentir o mundo enquanto o muda.", "Adaptação Crítica"),
    ("O riso é uma arma de desobediência civil.", "Laerte Coutinho"),
    ("Onde o sistema cria o deserto, a gente planta o jardim da fresta.", "Luiz Antonio Simas"),
    ("Viver é o exercício de não se deixar desencantar pelo mundo.", "Luiz Antonio Simas"),
    ("O corpo que ginga é o corpo que o colonizador não consegue segurar.", "Luiz Rufino"),
    ("A memória do samba é a prova de que a alegria é uma tecnologia de cura.", "Luiz Antonio Simas"),
    ("Subvertendo o tédio com um segundo de espanto.", "Inspirado em Simas"),
    ("Sonhar é o ensaio para o futuro que a gente quer construir.", "Sidarta Ribeiro"),
    ("A memória é o que nos permite ser fio e não apenas rastro.", "Sidarta Ribeiro"),
    ("Narrar o dia é organizar o caos interno. Grave o seu hoje.", "Sidarta Ribeiro"),
    ("O cérebro precisa de pausas para criar sentidos. Qual foi sua pausa hoje?", "Sidarta Ribeiro"),
    ("Eu sou apenas um rapaz latino-americano sem dinheiro no banco... mas com história.", "Belchior"),
    ("Respeito muito minhas lágrimas, mas ainda mais minha risada.", "Gal Costa"),
    ("A gente tem que estar atento e forte.", "Gal Costa"),
    ("O povo sabe o que quer, mas o povo também quer o que não sabe.", "Gilberto Gil"),
    ("Nossa esperança é um risco que a gente corre.", "Chico Buarque"),
    ("É preciso amor para poder pulsar.", "Almir Sater"),
    ("O silêncio é a pior forma de esquecimento.", "Inspirado em Milton Nascimento"),
    ("Minha pele é o meu manifesto.", "Luedji Luna"),
    ("Ocupo meu lugar no mundo com a força de quem veio antes.", "Liniker"),
    ("Eu não vou morrer, eu vou virar semente.", "Marielle Franco"),
    ("Toda saudade é a presença de uma ausência que a gente decidiu guardar.", "Roberta Rocha"),
    ("O que a memória ama, fica eterno.", "Adélia Prado"),
    ("A vida não é útil, a vida é uma fruição.", "Ailton Krenak"),
    ("A liberdade é o direito de não ter que provar nada a ninguém.", "Ana Liz"),
    ("Seja a sua própria revolução de bolso.", "Angela Davis"),
    ("Tudo o que é sólido desmancha no ar, menos o que a gente registra com amor.", "Inspirado em Marx/Berman"),
    ("Grave o detalhe, o sistema não aguenta a subjetividade.", "Ana Liz"),
    ("O olhar não nos define, mas nos compõe.", "Roberta Rocha"),
    ("A felicidade é uma abstração cuja busca obsessiva produz ansiedade.", "Laerte Coutinho"),
    ("O pior que pode acontecer é melhor do que o melhor que pode não acontecer.", "Laerte Coutinho"),
    ("Ser gentil é muito punk.", "Laerte Coutinho"),
    ("Não há forma de matar a arte.", "Laerte Coutinho"),
    ("A gente sempre se acha o suprassumo da boa consciência.", "Laerte Coutinho"),
    ("O humor é um dos coloridos da linguagem humana.", "Laerte Coutinho"),
    ("A vida vale a pena, mas a gente esquece disso no caminho.", "Laerte Coutinho"),
    ("Não é questão de esperança, é questão de sobrevivência.", "Laerte Coutinho"),
    ("A gente não precisa deixar de rir nunca.", "Laerte Coutinho"),
    ("Onde o sistema cria o deserto, a gente planta a dúvida.", "Laerte Coutinho"),
    ("Nós vamos sorrir, mesmo que eles não queiram.", "Ainda Estou Aqui — Eunice Paiva"),
    ("Eu não sou o que aconteceu comigo, eu sou o que sobrou de mim.", "Ainda Estou Aqui"),
    ("Se for, vá em paz. Se vier, venha por bem.", "Bacurau"),
    ("Quem nasce em Bacurau é o quê? É gente.", "Bacurau"),
    ("A senhora não sabe o que é ter que esquecer para poder viver.", "Central do Brasil"),
    ("Não esqueça de mim. Josué, eu tenho esperança que um dia você vai ler isso.", "Central do Brasil"),
    ("Onde foi que você aprendeu que o mundo era seu?", "Que Horas Ela Volta?"),
    ("A gente não precisa de patrão, a gente precisa de dignidade.", "Eles Não Usam Black-Tie"),
    ("O sertão vai virar mar e o mar vai virar sertão.", "Deus e o Diabo na Terra do Sol"),
    ("Minha história não cabe em uma ficha de polícia.", "Pixote"),
    ("Eu sou porque nós somos.", "Marielle Franco"),
    ("Não serei interrompida. Minha voz é o eco de muitas.", "Marielle Franco"),
    ("Não se sobrecarregue com o que o sistema impõe. Sobreviver já é uma vitória.", "Erika Hilton"),
    ("O poder deve servir para que as pessoas possam ser quem são.", "Erika Hilton"),
    ("Eles podem cortar as flores, mas não podem deter a primavera.", "Pablo Neruda"),
    ("Minha pátria é o chão que eu piso e as mãos que eu aperto.", "Pepe Mujica"),
    ("Viver com sobriedade é ser livre para gastar tempo com o que se ama.", "Pepe Mujica"),
    ("Cozinhar é um ato político. Comer é um ato de soberania.", "Bela Gil"),
    ("O tempero da nossa história é a memória de quem cozinhou antes de nós.", "Dona Canô"),
    ("A mesa é o único lugar onde o mundo faz sentido por um instante.", "Paola Carosella"),
    ("Não há nada mais revolucionário do que comer o que a terra dá.", "Lideranças do MST"),
    ("A cozinha é o coração da casa, e a memória é o fogo que a mantém acesa.", "Provérbio Popular"),
    ("Dividir o pão é a base de qualquer revolução verdadeira.", "Filosofia de Base"),
    ("O que a gente come diz de onde a gente veio e para onde queremos ir.", "Inspirado em Josué de Castro"),
    ("A nossa organização é a nossa única defesa.", "Frantz Fanon"),
    ("Não há revolução sem a alegria das ruas e o barulho dos tambores.", "Pensamento Radical"),
    ("A vida é uma teia, não uma pirâmide. Ocupe sua posição na rede.", "Cosmovisão Indígena"),
    ("Organizar o ódio para transformar o mundo.", "Frase de Movimentos Sociais"),
    ("Nossa espiritualidade é com a terra e com os ancestrais, sem intermediários.", "Pensamento Decolonial"),
    ("Onde não há justiça, que não haja paz.", "Muro da Cidade"),
    ("A cidade é nossa de quem a caminha.", "Pixo / Movimento Urbano"),
    ("Existimos porque resistimos.", "Frase de Rua"),
    ("Seja a mudança que o sistema não consegue prever.", "Muro"),
    ("O amor é um ato revolucionário entre iguais.", "Frase de Rua"),
    ("Dê o drible no tédio: a vida acontece na curva, não na reta.", "Luiz Antonio Simas"),
    ("A tecnologia sem ancestralidade é apenas uma ferramenta de controle.", "Tiganá Santana"),
    ("Descolonizar o tempo é parar de contar as horas e começar a contar os afetos.", "Geni Núñez"),
    ("O algoritmo tenta te prever, o registro te permite se surpreender.", "Ana Liz"),
    ("A gente se organiza na fresta, onde o estado não alcança.", "Luiz Antonio Simas"),
    ("A revolução será filmada por nós, em um segundo de cada vez.", "Gil Scott-Heron"),
    ("O sistema te quer mudo, a gente te quer berrando.", "Poesia de Rua"),
    ("Não sou descendente de escravos, sou descendente de seres humanos escravizados.", "Slam Resistência"),
    ("A paz sem voz não é paz, é medo.", "O Rappa"),
    ("Minha história não cabe no seu gráfico de estatística.", "Slam do Onze"),
    ("Seja o erro no algoritmo do sistema.", "Poesia Digital"),
    ("A gente sobreviveu ao ontem para hackear o amanhã.", "Doralice"),
    ("Minha voz tem sotaque de luta e cor de liberdade.", "Doralice"),
    ("Ocupar o topo é pouco, a gente quer é mudar a base.", "Doralice"),
    ("O amor é o único drible que o capitalismo não prevê.", "Slam de Quebrada"),
    ("Minha rima é o espelho que a cidade tenta quebrar.", "Doralice"),
    ("Não é só sobre falar, é sobre ser ouvida.", "Doralice"),
    ("O tempo da escrita é o tempo da cura.", "Socorro Acioli"),
    ("Histórias são âncoras que a gente lança no tempo.", "Socorro Acioli"),
    ("O passado não é morada, é mapa.", "Socorro Acioli"),
    ("O silêncio das pedras guarda a história do mundo.", "Filosofia da Terra"),
    ("A alegria é o nosso maior contra-ataque.", "Pixo de Rua"),
    ("O tempo não é linha, é rastro de pés que dançam.", "Luiz Rufino"),
    ("Onde o sistema cria deserto, a gente planta fresta.", "Luiz Antonio Simas"),
    ("Viver é não se deixar desencantar.", "Luiz Antonio Simas"),
    ("A minha inteligência não tem sotaque.", "Gloria Anzaldúa"),
    ("Falar \"errado\" é descolonizar a língua.", "Lélia Gonzalez"),
    ("Não serei interrompida.", "Marielle Franco"),
    ("A liberdade é uma prática.", "Angela Davis"),
    ("A gente só conhece o mundo quando o transforma.", "Darcy Ribeiro"),
    ("O registro de hoje é munição para amanhã.", "Frantz Fanon"),
    ("Nossa memória é tecnologia de sobrevivência.", "Daiara Tukano"),
    ("A terra é o nosso corpo.", "Sônia Guajajara"),
    ("A beleza é um direito.", "Jéssica Balbino"),
    ("A ternura é uma ferramenta política.", "Chimamanda Ngozi Adichie"),
    ("Minha vida é meu único território soberano.", "Suheir Hammad"),
    ("Não há nada mais político que a nossa alegria.", "Abigail Campos Leal"),
    ("Descolonizar o olhar é ver beleza na nossa história.", "Geni Núñez"),
    ("Sua existência é um documento histórico.", "Ana Liz"),
    ("Esquecimento é apagamento.", "Ana Liz"),
    ("A vida transborda no detalhe.", "Ana Liz"),
    ("Falar \"errado\" é a língua que o povo inventou.", "Mano Brown"),
    ("A memória é uma construção de afeto e invenção.", "Socorro Acioli"),
    ("Existem segredos que só o tempo tem paciência de contar.", "Socorro Acioli"),
    ("Dançar é uma forma de oração sem palavras e sem dogmas.", "Corpo e Movimento"),
    ("A força de uma mulher vem das que vieram antes dela.", "Ancestralidade Feminina"),
    ("A imagem é o que nos resta quando o tempo tenta nos apagar.", "Ana Liz"),
    ("Minha ancestralidade é o feitiço que o tempo não quebra.", "Sabedoria Ancestral"),
    ("Somos as netas das bruxas que vocês não conseguiram queimar.", "Tish Thawer"),
    ("O mar guarda segredos que a terra ainda não aprendeu a ouvir.", "Iemanjá"),
    ("Ser bruxa é retomar o controle sobre o próprio corpo e destino.", "Bruxaria Política"),
    ("A palavra é o primeiro ebó: o que você diz, você cria.", "Filosofia Yorubá"),
    ("Minha intuição é a bússola que o sistema não consegue desviar.", "Saberes Femininos"),
    ("Onde há mulher, há magia e há política.", "Buchi Emecheta"),
    ("Não se cura o que não se tem coragem de olhar.", "Sabedoria de Benzedeira"),
    ("O tempo das águas é o tempo do sentir.", "Filosofia das Águas"),
    ("O silêncio é uma arma, mas a fala é a cura.", "Tsitsi Dangarembga"),
    ("Minha força vem da terra que me sustenta e do céu que me guia.", "Sabedoria Matriarcal"),
    ("Feitiço é intenção colocada em movimento.", "Bruxaria Natural"),
    ("O que a boca cala, o corpo grita.", "Sabedoria Popular"),
    ("Ser livre é não ter medo de ser estranha ao mundo.", "Pensamento Radical"),
    ("A memória é um rio que corre para trás e para frente ao mesmo tempo.", "Filosofia Africana"),
    ("O conhecimento é a única herança que ninguém pode confiscar.", "Tsitsi Dangarembga"),
    ("Meu corpo é meu altar, minha história é meu rito.", "Pensamento Radical"),
    ("A lua não brilha sem a escuridão, e nós também não.", "Ciclos Lunares"),
    ("O axé não se explica, se sente e se vive.", "Sabedoria de Terreiro"),
    ("Nada acontece antes do tempo da maturação.", "Sabedoria da Terra"),
    ("Às vezes a gente só precisa de um culpado e o capitalismo é ótimo nisso.", "Isadora Não Entende Nada"),
    ("O cansaço não é um erro de percurso, é o projeto.", "Isadora Não Entende Nada"),
    ("Autocuidado sem consciência de classe é só consumo.", "Isadora Não Entende Nada"),
    ("Você não é difícil de amar, as pessoas é que são preguiçosas.", "Isadora Não Entende Nada"),
    ("Romantizar o sofrimento é a armadilha mais antiga do mundo.", "Isadora Não Entende Nada"),
    ("A gente precisa parar de pedir desculpas por existir.", "Isadora Não Entende Nada"),
    ("Estar exausta num mundo louco é um sinal de sanidade.", "Isadora Não Entende Nada"),
    ("Não tem como ser gratiluz pagando boleto.", "Isadora Não Entende Nada"),
    ("A nossa solidão também é um sintoma político.", "Isadora Não Entende Nada"),
    ("Menos produtividade, mais direito ao tédio.", "Isadora Não Entende Nada"),
    ("O amanhã não está à venda.", "Ailton Krenak"),
    ("Não importa o tamanho do caos, sempre separar um tempo pra ser feliz.", "Isadora Não Entende Nada"),
    ("O sistema lucra com a nossa pressa. Desacelere por um segundo.", "Isadora Não Entende Nada"),
    ("Sua saúde mental não deveria ser um luxo de quem tem dinheiro.", "Isadora Não Entende Nada"),
    ("A subjetividade é a única coisa que o algoritmo não consegue copiar.", "Paul B. Preciado"),
    ("Ser livre é o direito de não ser definido por ninguém.", "Paul B. Preciado"),
    ("Liberdade é pouco, o que eu desejo ainda não tem nome!", "Clarice Lispector"),
    ("O fogo que me queimaria ontem, hoje é o que ilumina meu caminho.", "Sabedoria de Bruxa"),
    ("Até cortar os próprios defeitos pode ser perigoso. Nunca se sabe qual é o defeito que sustenta nosso edifício.", "Clarice Lispector"),
    ("O que sou, é. Não se explica.", "Clarice Lispector"),
    ("Renda-se como eu me rendi. Mergulhe no que você não conhece.", "Clarice Lispector"),
    ("Escrevo para me livrar de mim.", "Clarice Lispector"),
    ("O instante é um luxo.", "Clarice Lispector"),
    ("Que ninguém se engane, só se consegue a simplicidade através de muito trabalho.", "Clarice Lispector"),
    ("Sou o que os outros pensam? Ou o que sinto que sou?", "Clarice Lispector"),
    ("A amizade feminina é o quilombo que o patriarcado não entende.", "Mariama Bâ"),
    ("Nada é tão urgente que não possa esperar um segundo de paz.", "Ana Liz"),
    ("O que o seu eu de amanhã diria sobre hoje?", "Retro1"),
  ];
}
